services:
    _defaults:
        autowire: false
        autoconfigure: false

    _instanceof:
        ChooseMyCompany\Shared\Domain\Service\ResetState:
            tags: [ { name: 'kernel.reset', method: reset } ]

    # ----------------------------------------------------
    # Presenters
    # ----------------------------------------------------
    presenter_process_domain:
        class: ChooseMyCompany\Shared\Presentation\Domain\ProcessDomainPresenter

    presenter_process_json:
        class: ChooseMyCompany\Shared\Presentation\Json\ProcessJsonPresenter
        arguments:
            $errorsOutcome: '@presenter_error_list_json'
            $processOutcome: '@presenter_process_domain'

    presenter_process_mercure:
        class: ChooseMyCompany\Shared\Presentation\Mercure\ProcessMercurePresenter
        arguments:
            $processProvider: '@presenter_process_domain'

    presenter_error_list_mercure:
        class: ChooseMyCompany\Shared\Presentation\Mercure\ErrorListMercurePresenter
        arguments:
            $errorsProvider: '@presenter_error_list_domain'
            $processProvider: '@presenter_process_domain'

    # ----------------------------------------------------
    # Message bus (middleware)
    # ----------------------------------------------------
    message_bus_middleware_add_process_stamp:
        class: ChooseMyCompany\Shared\Infrastructure\MessageBus\Messenger\Middleware\AddProcessStampMiddleware
        arguments:
            $processOutcome: '@presenter_process_domain'

    message_bus_middleware_process_loaded_event:
        class: ChooseMyCompany\Shared\Infrastructure\MessageBus\Messenger\Middleware\ProcessLoadedEventMiddleware
        arguments:
            $eventDispatching: '@event_bus_dispatcher'

    # ----------------------------------------------------
    # Event bus (event listener)
    # ----------------------------------------------------
    event_listener_process_present_on_loaded:
        class: ChooseMyCompany\Shared\Domain\EventListener\PresentProcessOnProcessLoadedEventListener
        arguments:
            $processPresenter: '@presenter_process_domain'
        tags: [ kernel.event_listener ]

    # ----------------------------------------------------
    # Broadcaster
    # ----------------------------------------------------
    process_update_factory_mercure:
        class: ChooseMyCompany\Shared\Infrastructure\Broadcast\Mercure\Factory\MercureProcessUpdateFactory
        arguments:
            $processProvider: '@presenter_process_domain'
            $serializer: '@serializer'

    process_broadcaster_mercure:
        class: ChooseMyCompany\Shared\Infrastructure\Broadcast\Mercure\Publisher\MercureBroadcaster
        arguments:
            $updateCreation: '@process_update_factory_mercure'
            $hub: '@mercure.hub.default.traceable'

    # ----------------------------------------------------
    # Attachers
    # ----------------------------------------------------
    process_attacher_view_model_mercure:
        class: ChooseMyCompany\Shared\Domain\Attacher\Process\ProcessViewModelCallbackAttacher
        abstract: true
        arguments:
            $processProvider: '@presenter_process_domain'
            $viewModelAccess: '@presenter_process_mercure'

    process_attacher_view_model_started_mercure:
        parent: process_attacher_view_model_mercure
        class: ChooseMyCompany\Shared\Domain\Attacher\Process\StartedProcessViewModelCallbackAttacher

    process_attacher_view_model_in_progress_mercure:
        parent: process_attacher_view_model_mercure
        class: ChooseMyCompany\Shared\Domain\Attacher\Process\InProgressProcessViewModelCallbackAttacher

    process_attacher_view_model_completed_mercure:
        parent: process_attacher_view_model_mercure
        class: ChooseMyCompany\Shared\Domain\Attacher\Process\CompletedProcessViewModelCallbackAttacher

    process_attacher_view_model_failed_mercure:
        parent: process_attacher_view_model_mercure
        class: ChooseMyCompany\Shared\Domain\Attacher\Process\FailedProcessViewModelCallbackAttacher

    process_attacher_view_model_failed_error_list_mercure:
        parent: process_attacher_view_model_mercure
        class: ChooseMyCompany\Shared\Domain\Attacher\Process\FailedProcessViewModelCallbackAttacher
        arguments:
            $viewModelAccess: '@presenter_error_list_mercure'

    process_attacher_notification_process_mercure:
        class: ChooseMyCompany\Shared\Domain\Attacher\Process\ProcessBroadcastingCallbackAttacher
        arguments:
            $processProvider: '@presenter_process_domain'
            $broadcasting: '@process_broadcaster_mercure'

    process_attacher_state_change_mercure:
        class: ChooseMyCompany\Shared\Domain\Attacher\MultipleAttacher
        arguments:
            - '@process_attacher_view_model_started_mercure'
            - '@process_attacher_view_model_in_progress_mercure'
            - '@process_attacher_view_model_completed_mercure'
            - '@process_attacher_view_model_failed_mercure'
            - '@process_attacher_notification_process_mercure'

    # ----------------------------------------------------
    # Initiation
    # ----------------------------------------------------
    process_initiation:
        class: ChooseMyCompany\Shared\Domain\Initiation\ProcessInitiation
        arguments:
            $identifierGeneration: '@generation_identifier'
            $processPresenter: '@presenter_process_domain'

    process_initiation_attacher_mercure:
        class: ChooseMyCompany\Shared\Domain\Initiation\AttacherInitiation
        arguments:
            $attacher: '@process_attacher_state_change_mercure'

    process_initiation_start:
        class: ChooseMyCompany\Shared\Domain\Initiation\ProcessStartInitiation
        arguments:
            $processProvider: '@presenter_process_domain'

    process_initiation_mercure:
        class: ChooseMyCompany\Shared\Domain\Initiation\MultipleInitiation
        arguments:
            $initiations:
                - '@process_initiation_attacher_mercure'
                - '@process_initiation_start'

    # ----------------------------------------------------
    # Completion
    # ----------------------------------------------------
    process_completion_progress:
        class: ChooseMyCompany\Shared\Domain\Completion\ProcessProgressCompletion
        arguments:
            $processProvider: '@presenter_process_domain'

    process_completion_finalize:
        class: ChooseMyCompany\Shared\Domain\Completion\ProcessFinalizeCompletion
        arguments:
            $errorOutcome: '@presenter_error_list_domain'
            $processProvider: '@presenter_process_domain'
