services:
    _defaults:
        autowire: false
        autoconfigure: false

    # ----------------------------------------------------
    # Identifiers
    # ----------------------------------------------------
    generation_identifier:
        class: ChooseMyCompany\Shared\Infrastructure\Identifier\Symfony\SymfonyIdentifierGeneration
        arguments:
            $uuidFactory: '@uuid.factory'

    # ----------------------------------------------------
    # Event bus (dispatcher)
    # ----------------------------------------------------
    event_bus_dispatcher:
        class: ChooseMyCompany\Shared\Infrastructure\EventBus\Symfony\Dispatcher\SymfonyEventDispatcher
        arguments:
            $eventDispatcher: '@event.dispatcher'

    # ----------------------------------------------------
    # Message bus (dispatcher)
    # ----------------------------------------------------
    envelope_factory:
        class: ChooseMyCompany\Shared\Infrastructure\MessageBus\Messenger\Factory\EnvelopeFactory

    message_bus_dispatcher:
        class: ChooseMyCompany\Shared\Infrastructure\MessageBus\Messenger\Dispatcher\MessengerMessageDispatcher
        arguments:
            $bus: '@command.bus'
            $envelopeFactory: '@envelope_factory'
